# Generated by Django 4.2 on 2023-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("mac_address", models.CharField(max_length=17)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, default=None, null=True),
                ),
                (
                    "last_wake",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_active", models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
