# Generated by Django 4.2 on 2023-04-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="wake_error",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
