# Generated by Django 4.2 on 2023-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0002_machine_wake_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="last_ping",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
